/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: [
    './index.html',
    './src/**/*.{js,ts,jsx,tsx}',
  ],
  theme: {
    extend: {
      colors: {
        'on-tertiary-fixed-variant': '#5516be',
        'inverse-on-surface': '#313032',
        'secondary-container': '#03b5d3',
        'surface': '#131315',
        'inverse-surface': '#e5e1e4',
        'on-primary': '#1000a9',
        'surface-container-lowest': '#0e0e10',
        'on-tertiary': '#3c0091',
        'on-surface-variant': '#c7c4d7',
        'outline-variant': '#464554',
        'on-surface': '#e5e1e4',
        'tertiary-fixed-dim': '#d0bcff',
        'on-primary-fixed': '#07006c',
        'surface-variant': '#353437',
        'error-container': '#93000a',
        'on-secondary-fixed': '#001f26',
        'outline': '#908fa0',
        'on-secondary-fixed-variant': '#004e5c',
        'on-background': '#e5e1e4',
        'on-primary-fixed-variant': '#2f2ebe',
        'on-error-container': '#ffdad6',
        'error': '#ffb4ab',
        'on-tertiary-container': '#340080',
        'primary': '#c0c1ff',
        'surface-container-highest': '#353437',
        'on-secondary': '#003640',
        'surface-container-high': '#2a2a2c',
        'tertiary-container': '#a078ff',
        'secondary-fixed': '#acedff',
        'on-tertiary-fixed': '#23005c',
        'on-primary-container': '#0d0096',
        'tertiary': '#d0bcff',
        'on-error': '#690005',
        'secondary-fixed-dim': '#4cd7f6',
        'primary-fixed-dim': '#c0c1ff',
        'primary-fixed': '#e1e0ff',
        'inverse-primary': '#494bd6',
        'surface-container-low': '#1c1b1d',
        'surface-tint': '#c0c1ff',
        'tertiary-fixed': '#e9ddff',
        'surface-dim': '#131315',
        'surface-container': '#201f22',
        'background': '#09090B',
        'secondary': '#4cd7f6',
        'primary-container': '#8083ff',
        'on-secondary-container': '#00424e',
        'surface-bright': '#39393b',
      },
      spacing: {
        'base': '8px',
        'stack-md': '24px',
        'stack-sm': '12px',
        'card-gap': '32px',
        'container-padding': '24px',
        'section-gap': '120px',
      },
      fontFamily: {
        'label-md': ['Geist', 'sans-serif'],
        'display-lg': ['Space Grotesk', 'sans-serif'],
        'body-lg': ['Inter', 'sans-serif'],
        'headline-md': ['Space Grotesk', 'sans-serif'],
        'display-lg-mobile': ['Space Grotesk', 'sans-serif'],
        'body-md': ['Inter', 'sans-serif'],
        'code': ['Geist', 'monospace'],
        'headline-lg': ['Space Grotesk', 'sans-serif'],
      },
      fontSize: {
        'label-md': ['14px', { lineHeight: '20px', letterSpacing: '0.02em', fontWeight: '500' }],
        'display-lg': ['72px', { lineHeight: '80px', letterSpacing: '-0.04em', fontWeight: '700' }],
        'body-lg': ['18px', { lineHeight: '28px', fontWeight: '400' }],
        'headline-md': ['32px', { lineHeight: '40px', letterSpacing: '-0.01em', fontWeight: '600' }],
        'display-lg-mobile': ['40px', { lineHeight: '44px', letterSpacing: '-0.02em', fontWeight: '700' }],
        'body-md': ['16px', { lineHeight: '24px', fontWeight: '400' }],
        'code': ['14px', { lineHeight: '20px', fontWeight: '400' }],
        'headline-lg': ['48px', { lineHeight: '56px', letterSpacing: '-0.02em', fontWeight: '600' }],
      },
    },
  },
  plugins: [],
};
